name: jamesboard
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17 # 최신 버전 확인 후 적용
  cupertino_icons: ^1.0.8

  # rating bar
  flutter_rating_bar: ^4.0.1

  # logger:
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  #이미지
  assets:
    - assets/image/

  # 폰트
  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
    - family: IcStar
      fonts:
        - asset: assets/fonts/IcStar.ttf